//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTable
    {
        public int IdAdmin { get; set; }
        public int IdClienteRede { get; set; }
        public int IdCliente { get; set; }
        public string UserNameAdmin { get; set; }
        public string PasswordAdmin { get; set; }
        public string PasswordConfirmation { get; set; }
    
        public virtual RedeTable RedeTable { get; set; }
        public virtual ClienteTable ClienteTable { get; set; }
    }
}
