//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteTable()
        {
            this.AdminTable = new HashSet<AdminTable>();
            this.ReservaTable = new HashSet<ReservaTable>();
        }
    
        public int IdCliente { get; set; }
        public string NomeCliente { get; set; }
        public int ContaBancaria { get; set; }
        public string PasswordCliente { get; set; }
        public byte[] ImagemCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminTable> AdminTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaTable> ReservaTable { get; set; }
    }
}
