//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseTemaAEntities4 : DbContext
    {
        public DatabaseTemaAEntities4()
            : base("name=DatabaseTemaAEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTable { get; set; }
        public virtual DbSet<ClienteTable> ClienteTable { get; set; }
        public virtual DbSet<EstacaoTable> EstacaoTable { get; set; }
        public virtual DbSet<HoraTable> HoraTable { get; set; }
        public virtual DbSet<PostoTable> PostoTable { get; set; }
        public virtual DbSet<RedeTable> RedeTable { get; set; }
        public virtual DbSet<ReservaTable> ReservaTable { get; set; }
    }
}
