//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostoTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostoTable()
        {
            this.HoraTable = new HashSet<HoraTable>();
            this.ReservaTable = new HashSet<ReservaTable>();
        }
    
        public int IdPosto { get; set; }
        public float PrecoPosto { get; set; }
        public int IdEstacao { get; set; }
    
        public virtual EstacaoTable EstacaoTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoraTable> HoraTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaTable> ReservaTable { get; set; }
    }
}
