//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedeTable()
        {
            this.AdminTable = new HashSet<AdminTable>();
        }
    
        public int IdClienteRede { get; set; }
        public string NomeRede { get; set; }
        public string UserName { get; set; }
        public int IdRede { get; set; }
        public byte[] ImagemRede { get; set; }
        public int IdEstacao { get; set; }
        public string PasswordClienteRede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminTable> AdminTable { get; set; }
        public virtual EstacaoTable EstacaoTable { get; set; }
    }
}
