//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTemaA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaTable()
        {
            this.EstacaoTable = new HashSet<EstacaoTable>();
        }
    
        public int IdReserva { get; set; }
        public int IdCliente { get; set; }
        public int IdPosto { get; set; }
        public float PrecoFinal { get; set; }
        public int EstadoReserva { get; set; }
        public System.DateTime DataReservaInicio { get; set; }
        public System.DateTime DataReservaFinal { get; set; }
    
        public virtual ClienteTable ClienteTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstacaoTable> EstacaoTable { get; set; }
        public virtual PostoTable PostoTable { get; set; }
    }
}
